 
# Add awaiting review label to all PRs-
# awaiting_review:
# - any: ['./*', 'bot/*']
# Add documentation label-
awaiting review:
  - ./*
  - cogs/*
  - utils/*
  - .github/*/*

documentation: 
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE
  - .all-contributorsrc
  - .github/ISSUE_TEMPLATE/*
 


enhancement:
  - cogs/*.py
  - utils/*.py
# - all: ['!.github/workflows/*', '!.github/resources/*']
